# Generated by Django 5.2.6 on 2026-05-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
    ]
