# Generated by Django 6.0.5 on 2026-05-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0004_alter_sharelink_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='share_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_notifications', to='AppAPI.permission'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='share_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
